version: '2.3'
services:
  dev:
    container_name: jmpbp
    image: jmpbp:latest
    runtime: nvidia
    #command: jupyter lab --port 8888 --ip=0.0.0.0 --allow-root
    working_dir: /home/***/Programs/JMPBP
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/***/Programs:/home/***/Programs
        - /data/:/data
    environment:
        - DISPLAY=unix$DISPLAY
        - TERM=xterm-256color
        - GRANT_SUDO:"yes"
    ports:
        - "8888:8888"
        - "6006:6006"
    ulimits:
        memlock: -1
        stack: 67108864
    shm_size: 128g
    #stdin_open: true
    tty: true
